---
sun:
  latitude: !secret latitude
  longitude: !secret longitude
  id: home_sun
  on_sunset:
    - elevation: -3.5°
      then:
        - select.set:
            id: brightness_mode
            option: "Evening"
  on_sunrise:
    - then:
        - select.set:
            id: brightness_mode
            option: "Day"

time:
  - platform: homeassistant
    id: system_time
    on_time_sync:
      - if:
          condition:
            lambda: 'return id(device_last_restart).state == "";'
          then:
            - text_sensor.template.publish:
                id: device_last_restart
                state: !lambda 'return id(system_time).now().strftime("%a %d %b %Y - %H:%M:%S");'
            - script.execute: set_brightness_mode_by_time
    on_time:
      - seconds: 0
        minutes: $screen_night_minute
        hours: $screen_night_hour
        then:
          - select.set:
              id: brightness_mode
              option: "Night"
      - minutes: '*'
        seconds: 0
        then:
          - script.execute: time_update


lvgl:
  on_idle:
    timeout: !lambda 'return id(touchscreen_idle_timeout_sec) * 1000;' #$touchscreen_idle_timeout
    then:
      - logger.log: "LVGL is idle"
      - if:
          condition:
            - lambda: 'return id(brightness_mode).current_option() == "Day";'
          then:
            - light.turn_on:
                id: display_backlight
                brightness: !lambda 'return id(touchscreen_daytime_brightness) / 100.0;' #${touchscreen_daytime_brightness}
      - if:
          condition:
            - lambda: 'return id(brightness_mode).current_option() == "Evening";'
          then:
            - light.turn_on:
                id: display_backlight
                brightness: !lambda 'return id(touchscreen_evening_brightness) / 100.0;' #${touchscreen_evening_brightness}
      - if:
          condition:
            - lambda: 'return id(brightness_mode).current_option() == "Night";'
          then:
            - light.turn_on:
                id: display_backlight
                brightness: !lambda 'return id(touchscreen_nighttime_brightness) / 100.0;' #${touchscreen_nighttime_brightness}
            - lvgl.pause:
                show_snow: false

# Wake on screen touch
touchscreen:
    on_touch:
      then:
        - script.execute: backlight_timeout_off
        - logger.log: "LVGL is active"
        - lvgl.resume
        - lvgl.widget.redraw
        - if:
            condition:
              - lambda: 'return id(brightness_mode).current_option() == "Day";'
            then:
              - light.turn_on:
                  id: display_backlight
                  brightness: !lambda 'return id(touchscreen_daytime_brightness) / 100.0;' #${touchscreen_daytime_brightness}
        - if:
            condition:
              - lambda: 'return id(brightness_mode).current_option() == "Evening";'
            then:
              - light.turn_on:
                  id: display_backlight
                  brightness: !lambda 'return id(touchscreen_evening_brightness) / 100.0;' #${touchscreen_evening_brightness}
        - if:
            condition:
              - lambda: 'return id(brightness_mode).current_option() == "Night";'
            then:
              - light.turn_on:
                  id: display_backlight
                  brightness: !lambda 'return id(touchscreen_nighttime_brightness) / 100.0;' #${touchscreen_nighttime_brightness}

select:
  - platform: template
    name: "Brightness mode"
    id: brightness_mode
    icon: mdi:television-shimmer
    optimistic: true
    options:
      - Day
      - Evening
      - Night
    initial_option: Night
    on_value:
      then:
        - script.execute: backlight_timeout_off
        - lvgl.resume
        - lvgl.widget.redraw
        - if:
            condition:
              - lambda: 'return id(brightness_mode).current_option() == "Day";'
            then:
              - light.turn_on:
                  id: display_backlight
                  brightness: !lambda 'return id(touchscreen_daytime_brightness) / 100.0;'
        - if:
            condition:
              - lambda: 'return id(brightness_mode).current_option() == "Evening";'
            then:
              - light.turn_on:
                  id: display_backlight
                  brightness: !lambda 'return id(touchscreen_evening_brightness) / 100.0;'
        - if:
            condition:
              - lambda: 'return id(brightness_mode).current_option() == "Night";'
            then:
              - light.turn_on:
                  id: display_backlight
                  brightness: !lambda 'return id(touchscreen_nighttime_brightness) / 100.0;'

script: 
  - id: backlight_timeout_off 
    mode: restart 
    then: 
      - delay: !lambda 'return id(touchscreen_idle_timeout_sec) * 1000;'
      - logger.log: "Backlight timeout reached"

      # Modalità DAY
      - if:
          condition:
            lambda: 'return id(brightness_mode).current_option() == "Day";'
          then:
            - light.turn_on:
                id: display_backlight
                brightness: !lambda 'return id(touchscreen_standby_day) / 100.0;'
            - lvgl.pause:
                show_snow: false

      # Modalità EVENING
      - if:
          condition:
            lambda: 'return id(brightness_mode).current_option() == "Evening";'
          then:
            - light.turn_on:
                id: display_backlight
                brightness: !lambda 'return id(touchscreen_standby_evening) / 100.0;'
            - lvgl.pause:
                show_snow: false

      # Modalità NIGHT
      - if:
          condition:
            lambda: 'return id(brightness_mode).current_option() == "Night";'
          then:
            - light.turn_on:
                id: display_backlight
                brightness: !lambda 'return id(touchscreen_standby_night) / 100.0;'
            - lvgl.pause:
                show_snow: false
                
  - id: set_brightness_mode_by_time
    then:
      - if:
          condition:
            lambda: 'return id(system_time).now().hour >= 6 && id(system_time).now().hour < 18;'
          then:
            - select.set:
                id: brightness_mode
                option: "Day"
      - if:
          condition:
            lambda: 'return (id(system_time).now().hour >= 18 && id(system_time).now().hour < 22) || (id(system_time).now().hour < 6 && !id(home_sun).is_above_horizon());'
          then:
            - select.set:
                id: brightness_mode
                option: "Evening"
      - if:
          condition:
            lambda: 'return id(system_time).now().hour >= 22 || id(system_time).now().hour < 6;'
          then:
            - select.set:
                id: brightness_mode
                option: "Night"


interval: 
  - interval: 60s 
    then: 
      - if:
          condition: lvgl.is_paused
          then:
            - lvgl.resume:
            - delay: 10s
            - lvgl.pause:
