---
# Switch toggle button
# vars:
#    uid:
#    row:
#    column:
#    row_span:
#    column_span:
#    text:
#    icon:
#    entity_id:
# slide_button.yaml

sensor:
  - platform: homeassistant
    id: ${number_id}
    name: number_${number_id} 
    entity_id: ${entity_id}
    on_value: 
      - lvgl.slider.update: 
          id: slider_${uid} 
          value: !lambda return x;
          
  - platform: template
    id: ${uid}_number_listener
    internal: true
    lambda: |-
      return id(${number_id}).state;
    update_interval: 1s
    on_value:
      - lvgl.label.update:
          id: value_${uid}
          text: !lambda |-
            char buffer[16];
            sprintf(buffer, "%.1f", id(${number_id}).state);
            return std::string(buffer);

lvgl:
  pages:
    - id: !extend ${page_id}
      widgets:
        - container:
            id: ${uid}
            grid_cell_row_pos: ${row}
            grid_cell_column_pos: ${column}
            grid_cell_row_span: ${row_span | default(1)}
            grid_cell_column_span: ${column_span | default(1)}
            grid_cell_x_align: stretch
            grid_cell_y_align: stretch
            widgets:

              - button:
                  id: button_${uid}

                  widgets:
                    - label:
                        id: icon_${uid}
                        text_font: $icon_font
                        align: top_left
                        text: ${icon}

                    - label:
                        id: label_${uid}
                        align: bottom_left
                        text: ${text}

                    # LABEL DEL VALORE (NUOVA)
                    - label:
                        id: value_${uid}
                        align: top_right
                        x: -5
                        y: -10
                        text: "0"

                    # SLIDER
                    - slider:
                        id: slider_${uid}
                        align: top_right
                        x: -5
                        y: 25
                        width: ${width}
                        height: ${height}
                        min_value: ${n_min}
                        max_value: ${n_max}
                        radius: 10

                        #knob:
                        #  pad_top: -5
                        #  pad_bottom: -5
                        #  transform_angle: 90
                        #  bg_color: $label_on_color

                        indicator:
                          radius: 0
                          bg_color: $label_off_color

                        on_release:
                          then:
                            - homeassistant.service:
                                service: input_number.set_value
                                data:
                                  entity_id: ${entity_id}
                                  value: !lambda 'return x;'


# Update visual state from HA
binary_sensor:
  - id: widget_sensor_${uid}
    platform: homeassistant
    entity_id: switch.${switch_state}
    trigger_on_initial_state: true
  
    on_state:
      - if:
          condition:
            binary_sensor.is_on: widget_sensor_${uid}
          then:
            - lvgl.widget.update:
                id: button_${uid}
                bg_color: $button_on_color
            - lvgl.widget.update:
                id: icon_${uid}
                text_color: $icon_on_color
            - lvgl.widget.update:
                id: label_${uid}
                text_color: $label_on_color
            - lvgl.widget.update:
                id: slider_${uid}
                knob:
                  bg_color: $label_on_color
          else:
            - lvgl.widget.update:
                id: button_${uid}
                bg_color: $button_off_color
            - lvgl.widget.update:
                id: icon_${uid}
                text_color: $icon_off_color
            - lvgl.widget.update:
                id: label_${uid}
                text_color: $label_off_color
            - lvgl.widget.update:
                id: slider_${uid}
                knob:
                  bg_color: $label_off_color


