---
# Switch (or light) toggle button
# vars:
#    uid:
#    row:
#    column:
#    row_span:
#    column_span:
#    text: 
#    icon:
#    entity_id:

# AGGIUNTA: Sensori template per l'aggiornamento automatico dei valori
sensor:
  - platform: template
    id: ${uid}_sensor_listener_m
    internal: true
    lambda: |-
      return id(${sensor_id_m}).state;
    update_interval: 10s
    on_value:
      then:
        - lvgl.label.update:
            id: mlabel_${uid}
            text: !lambda |-
              char buffer[16];
              sprintf(buffer, "%.2f", id(${sensor_id_m}).state);
              return std::string(buffer);

  - platform: template
    id: ${uid}_sensor_listener_b
    internal: true
    lambda: |-
      return id(${sensor_id_b}).state;
    update_interval: 10s
    on_value:
      then:
        - lvgl.label.update:
            id: blabel_${uid}
            text: !lambda |-
              char buffer[16];
              sprintf(buffer, "%.2f", id(${sensor_id_b}).state);
              return std::string(buffer);

lvgl:
  pages:
    - id: !extend ${page_id}
      widgets:
        - container:
              id: ${uid}
              grid_cell_row_pos: ${row}
              grid_cell_column_pos: ${column}
              grid_cell_row_span: ${row_span | default(1)}
              grid_cell_column_span: ${column_span | default(1)}
              grid_cell_x_align: stretch
              grid_cell_y_align: stretch
              # outline_width: 1
              # outline_color: red
              widgets:
              - obj:
                  id: obj_${uid}
                  styles: [button_style]
                  widgets:
                    - label:
                        align: top_left
                        id: tlabel_${uid}
                        text: ${ttext}
                        text_color: white
                    - label:
                        align: left_mid
                        id: mlabel_${uid}
                        text: ${mtext}
                        text_color: white
                    - label:
                        align: bottom_left
                        id: blabel_${uid}
                        text: ${btext}
                        text_color: white
                  #on_short_click:
                  #  then:
                  #    - lvgl.widget.refresh: tlabel_${uid}
                  #    - lvgl.widget.refresh: mlabel_${uid} 
                  #    - lvgl.widget.refresh: blabel_${uid}