sensor:
  - platform: template
    id: ${uid}_number_listener
    internal: true
    lambda: |-
      return id(${number_id}).state;
    update_interval: 1s
    on_value:
      - lvgl.label.update:
          id: value_${uid}
          text: !lambda |-
            char buffer[16];
            sprintf(buffer, "%.1f", id(${number_id}).state);
            return std::string(buffer);
      - lvgl.textarea.update:
          id: textarea_${uid}
          text: !lambda |-
            char buffer[16];
            sprintf(buffer, "%.1f", id(${number_id}).state);
            return std::string(buffer);

lvgl:
  pages:
    - id: !extend ${page_id}
      widgets:
        # Tastiera numerica LVGL 9
        - keyboard:
            id: keyboard_${uid}
            mode: LV_KEYBOARD_MODE_NUMBER
            textarea: textarea_${uid}

            on_value:
              then:
                - lambda: |-
                    if (x == LV_EVENT_READY) {
                      std::string val = id(textarea_${uid}).get_text();
                      float num = atof(val.c_str());

                      id(keyboard_${uid}).hide();
                      id(textarea_${uid}).clear_focus();

                      id(set_soglia_deu).trigger(num);
                    }


        - container:
            id: ${uid}
            grid_cell_row_pos: ${row}
            grid_cell_column_pos: ${column}
            grid_cell_row_span: ${row_span | default(1)}
            grid_cell_column_span: ${column_span | default(1)}
            grid_cell_x_align: stretch
            grid_cell_y_align: stretch

            widgets:

              - button:
                  id: button_${uid}

                  widgets:
                    - label:
                        id: icon_${uid}
                        text_font: $icon_font
                        align: top_left
                        text: ${icon}

                    - label:
                        id: label_${uid}
                        align: bottom_left
                        text: ${text}

                    # Valore numerico visualizzato
                    - label:
                        id: value_${uid}
                        align: top_right
                        x: -5
                        y: -10
                        text: "0"

                    # Textarea
                    - textarea:
                        id: textarea_${uid}
                        align: LV_ALIGN_TOP_RIGHT
                        x: -5
                        y: 15
                        width: lv_pct(30)
                        height: 40
                        one_line: true
                        text: "0"

                        on_focus:
                          then:
                            - lvgl.widget.show: keyboard_${uid}

# Update visual state from HA
binary_sensor:
  - id: widget_sensor_${uid}
    platform: homeassistant
    entity_id: switch.${switch_state}
    trigger_on_initial_state: true
  
    on_state:
      - if:
          condition:
            binary_sensor.is_on: widget_sensor_${uid}
          then:
            - lvgl.widget.update:
                id: button_${uid}
                bg_color: $button_on_color
            - lvgl.widget.update:
                id: icon_${uid}
                text_color: $icon_on_color
            - lvgl.widget.update:
                id: label_${uid}
                text_color: $label_on_color
            - lvgl.widget.update:
                id: textarea_${uid}
                text_color: $label_on_color
          else:
            - lvgl.widget.update:
                id: button_${uid}
                bg_color: $button_off_color
            - lvgl.widget.update:
                id: icon_${uid}
                text_color: $icon_off_color
            - lvgl.widget.update:
                id: label_${uid}
                text_color: $label_off_color
            - lvgl.widget.update:
                id: textarea_${uid}
                text_color: $label_off_color
